### PR TITLE
Move large file out of package.

### PR DESCRIPTION
**Pull request by dblodgett-usgs**
I think this should just work -- I tested it with the file in its current location and it seemed fine. 

I moved the 5.6mb zip out into a package that doesn't build into the package. It now downloads whenever it's requested. The pattern also allows us to add more sample data into the `docs/data/` folder with a companion 0b file to register that it is available.

### CODE REVIEW

**Comment by dblodgett-usgs** [comment]
@keller-mark -- I don't expect tests to pass until the github pages file has deployed. Once it's there, then it should, in thoery, work but there's a chance a little clean up will be necessary after that's done.

**Comment by keller-mark** [comment]
I am not sure this the best approach in the long-term but i am ok with it as it improves upon the prior approach

**Comment by dblodgett-usgs** [comment]
A ringing endorsement! I'll take it. 100% agree though -- this was just an easy way to improve on what we had.

**Comment by dblodgett-usgs** [comment]
hmmm... didn't realize that the build failing would block the pages deploy. That's a problem. We could switch the url to 

`https://github.com/keller-mark/pizzarr/raw/refs/heads/main/docs/data/dog.ome.zarr.zip` temporarily?

**Pull request merged**
