### PR TITLE
Doco

### PR DESCRIPTION
**Pull request by dblodgett-usgs**
Working through the package cleaning up documentation warnings printed by roxygen -- mostly just adding TODOs but did a little actual contribution in here.

(sorry for the false start -- realizing you squashed that last PR and wanted to clean up the history)

### CODE REVIEW

**Comment by dblodgett-usgs** [comment]
I'm working through the rest of the roxygen warnings -- I'm seeing the `@field` annotation on a lot of private fields -- looks like the `@field` documentation only goes on public fields? Just want to make sure you are aware I'm removing those.

**Comment by dblodgett-usgs** [comment]
image

**Comment by dblodgett-usgs** [comment]
Alright @keller-mark -- my local build round tripping roxygen2 is quiet now. I stupped in a lot of documentation with TODOs but did fill in quite a few with reasonably useful content. As I work on things going forward, I'll do my best to work on all these TODOs. Anything you would like me to change here before merging in?

**Review by keller-mark — APPROVED** [review]
Thanks! Looks good, will merge now. I did not know about the `@inheritParams` or the intended usage of `@field`

**Comment by dblodgett-usgs** [comment]
Awesome! I kind of want to go look at some of the ropensci packages for how they are using roxygen under R6. It's hard to reuse documentation without more direct inheretence -- which just isn't really built in at this point from what I see.

**Pull request merged**
